### PR TITLE
Custom logo and styles

### PR DESCRIPTION
**Pull request by smartin77**
Added env variables to add custom logo and css style from mounted source. See updated readme for details.

### CODE REVIEW

**Comment by microbearlogist** [comment]
Some update regarding this pull request?

**Comment by wheelybird** [comment]
To be frank I'm concerned about overloading the amount of configuration parameters there are.   This was only ever meant to be a simple UI for basic (mostly POSIX) account management.   I've already lost track of config options myself.
Saying that, looking at this PR again it doesn't seem to onerous and I can see the utility.  So I'll look at including this with the next update.

**Comment by microbearlogist** [comment]
Yes, I understand your reluctance to see the project stray (even further) from its original mission.

So thank you doubly for your understanding.

**Comment by microbearlogist** [comment]
> You are right, I understand your reluctance to see the project stray (even further) from its original mission.
> 
> So thank you doubly for your understanding.

**Comment by NetSamurai** [comment]
Appreciate this project greatly, +1 to this PR IMO, just reviewed the source change intents and this is much cleaner than mounting the entire `/opt/ldap-user-manager` folder to override styles.

**Comment by wheelybird** [comment]
@NetSamurai fair enough.  I'll try and merge/release this as soon as I get some time.

**Review by wheelybird — APPROVED** [review]

**Comment by voc0der** [comment]
I was able to test and build this..  it's `voc0der/ldap-user-manager:latest` 

https://hub.docker.com/r/voc0der/ldap-user-manager if someone else wants to use this version until its built.

Works great. Thanks!!

**Pull request merged**
