### PR TITLE
New user - Remove accents/diacritics from Username and Email while typing

### PR DESCRIPTION
**Pull request by smartin77**
Hello, this update will remove unsupported diacritic marks in Username and Email fields while adding Name and Surname

### CODE REVIEW

**Comment by wheelybird** [comment]
Thanks for the PR.  I've also got a request to allow unicode characters in the regex that validates user and group names, so there's a conflict there.  Is there a particular use case for this PR?

**Comment by smartin77** [comment]
I am not sure what you mean with particuler use case, but my update removes accent marks from usernames (eg. Jerguš Novotný) and make just username and emial following way jergus.novotny, jergus.novotny@myemail.com. Name and surname are kept untouched.

**Comment by wheelybird** [comment]
Thanks for this.  The username validation stuff is changing a bit in the next release, so I won't merge this. But I will include the javascript changes in that release.

**Comment by wheelybird** [comment]
This has been added to the latest release (v1.6).

**Pull request closed without merging**
